## spring security 配置
security:
  oauth2:
    client:
      client-id: ENC(gPFcUOmJm8WqM3k3eSqS0Q==)
      client-secret: ENC(gPFcUOmJm8WqM3k3eSqS0Q==)
      scope: server
      ignore-urls:
        - '/actuator/**'
        - '/v2/api-docs'
        - '/service/**'
        - '/editor-app/**'
        - '/task/view/*'
        - '/process/resource/**'
        - '/modeler.html'
spring:
  autoconfigure:
    exclude: org.activiti.spring.boot.SecurityAutoConfiguration
  activiti:
    check-process-definitions: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://pigx-mysql:3306/pigxx_ac?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
